services:
  webserver:
    image: app-api:latest
    networks:
      - caddy_public
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - runtime:/app/app/runtime
    environment:
      SERVER_NAME: ":80"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        caddy: app-api.example.com
        caddy.reverse_proxy: "{{upstreams 80}}"

volumes:
  caddy_data:
  caddy_config:
  runtime:

networks:
  caddy_public:
    external: true
