services:
  webserver:
    build:
      context: .
      target: dev
    container_name: app-api
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
      - runtime:/app/runtime
    tty: true

volumes:
  caddy_data:
  caddy_config:
  runtime:
