name: app-api
services:
  app:
    build:
      dockerfile: .docker/Dockerfile
      context: ..
      target: dev
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      YII_ENV: "dev"
      YII_DEBUG: true
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/app
      - caddy_data:/data
      - caddy_config:/config
      - ../runtime:/app/runtime
      - ${COMPOSER_CACHE_DIR:-~/.cache/composer}:/var/www/.composer
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  caddy_data:
  caddy_config:
