name: ${STACK_NAME}
services:
  app:
    build:
      dockerfile: .docker/Dockerfile
      context: ..
      target: dev
      args:
        UID: ${UID}
        GID: ${GID}
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      YII_ENV: "dev"
      YII_DEBUG: true
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/app
      - ../runtime:/app/runtime
      - ${COMPOSER_CACHE_DIR:-~/.cache/composer}:/var/www/.composer
      - caddy_data:/data
      - caddy_config:/config
    tty: true

