on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.env.example'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  push:
    branches: ['master']
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: build

jobs:
  build:
    uses: yiisoft/actions/.github/workflows/codeception.yml@master
    with:
      codeception-command: vendor/bin/codecept run Acceptance
#        vendor/bin/codecept build

      extensions: fileinfo, pdo, pdo_sqlite, intl
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1']
